server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: payment
          uri: http://localhost:8081
          predicates:
            - Path=/payments/** 
        - id: room
          uri: http://localhost:8082
          predicates:
            - Path=/rooms/**/reviews/** 
        - id: reservation
          uri: http://localhost:8083
          predicates:
            - Path=/reservations/** 
        - id: message
          uri: http://localhost:8084
          predicates:
            - Path=/messages/** 
        - id: viewpage
          uri: http://localhost:8085
          predicates:
            - Path= /roomviews/**
        - id: member
          uri: http://localhost:8086
          predicates:
            - Path=/members/** 
        - id: affiliateproduct
          uri: http://localhost:8087
          predicates:
            - Path=/affiliateproducts/** 
        - id: order
          uri: http://localhost:8088
          predicates:
            - Path=/orders/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: room
          uri: http://room:8080
          predicates:
            - Path=/rooms/**/reviews/** 
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/** 
        - id: message
          uri: http://message:8080
          predicates:
            - Path=/messages/** 
        - id: viewpage
          uri: http://viewpage:8080
          predicates:
            - Path= /roomviews/**
        - id: member
          uri: http://member:8080
          predicates:
            - Path=/members/** 
        - id: affiliateproduct
          uri: http://affiliateproduct:8080
          predicates:
            - Path=/affiliateproducts/** 
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080